### ISSUE TITLE
Integrate remaining Embeddings Providers

### ISSUE THREAD

**Issue by filopedraz** [premAI-io/prem-utils#25]
### Description

Check all the providers and see if they have embedding models exposed too. As [cohere](https://txt.cohere.com/introducing-embed-v3/) for example.

**Comment by filopedraz** [comment]
@giowe same for this one, but not high priority.

**Comment by albemordo** [comment]
Roadmap:
- [ ] Anthropic
- [x] OpenAI
- [ ] Perplexity
- [x] Cohere
- [ ] Perplexity
- [ ] Groq
- [ ] Mistral
- [ ] OpenRouter

**Comment by nsosio** [comment]
> @nsosio can you help with this plz ?

I'll look into it 🙂
