### ISSUE TITLE
Parameter Spec

### ISSUE THREAD

**Issue by nsosio** [premAI-io/prem-utils#86]
Update the `model.json` to include a parameters section for each model (not deprecated) with a `parameters` field specifying for each parameter:
- `default` 
- `min` (only for `max_tokens` and `temperature`)
- `max` (only for `max_tokens` and `temperature`)

> Note
> Specify default value for each parameter specified in the chat completion (e.g [openai](https://github.com/premAI-io/prem-utils/blob/main/prem_utils/connectors/openai.py#L74-L88))
> parameters["temperature"] = model_parameters.temperature
> parameters["top_p"] = model_parameters.top_p
> parameters["max_tokens"] = model_parameters.max_tokens
> parameters["presence_penalty"] = model_parameters.presence_penalty
> parameters["frequency_penalty"] = model_parameters.frequency_penalty
> parameters["logit_bias"] = model_parameters.logit_bias

**Comment by vittoriop17** [comment]
Docs:
- Azure
